### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by njbrown09** [pocesar/node-stratum#14]
The examples dont exactle show how to do anything. can you redo the examples?

**Comment by pocesar** [comment]
stratum is a protocol, this library implements the protocol, the implementation varies according to the digital currency (usually bitcoin and compatible coins) and miners that support those. the nonce, how the work is sent to the miner, are coin-dependant. that's why it has no 'concrete' example. it's not an out-of-the-box library like pool libraries, it's a lower level library
